<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="karima-hp" failures="1" tests="5" name="Test" time="21.691" errors="0" timestamp="26 Jun 2023 01:22:24 GMT">
  <testcase classname="code_7thfeb.FlipKart" name="flipkartTest" time="0.007"/>
  <testcase classname="code_7thfeb.Walmart" name="walmartTest" time="0.001"/>
  <testcase classname="code_7thfeb.Rediff" name="rediffTest" time="1.914">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Some reason">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Some reason
at code_7thfeb.Rediff.rediffTest(Rediff.java:42)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- rediffTest -->
  <testcase classname="code_7thfeb.Costco" name="costcoTest" time="0.001"/>
  <testcase classname="code_7thfeb.Amazon" name="amazonTest" time="0.001"/>
</testsuite> <!-- Test -->
